name: todo_demo
version: 1.0.0
description: todo_demo

environment:
  sdk: '>=1.18.1 <2.0.0'

dependencies:
  wdesk_sdk:
    hosted:
      name: wdesk_sdk
      url: https://pub.workiva.org
    version: ^0.6.10

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
